### ISSUE TITLE
 ms_should_be_final doesn't see 'protected' modifier (assumes it is public)

### ISSUE THREAD

**Issue by LoveenDyall** [spotbugs/spotbugs#1015]
```
public abstract class MyAbstractParent {

  protected static String vartoOverride = "child-classes-override-me";

}
```

I then override MyAbstractParent.vartoOverride using:

```
public class MyConcreteChild extends MyAbstractParent {

  static {
    vartoOverride = "overriden";
  }
}
```

Hi, the following class shows as a ms_should_be_final bug on findbugs-maven-plugin (artifactID).

The bugs code on sourceforge states:

> This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

but the field is clearly not public.

Am I missing something really obvious with using protected modifiers?

**Comment by ThrawnCA** [comment]
The first thing to note is, this is not a good code pattern, with subclasses changing a protected static variable.

Second, possibly the error message just needs adjustment. A `protected` variable still has the same problems, albeit on a smaller scale, since any subclass in any package can alter it.

**Comment by LoveenDyall** [comment]
Yup, I was told the same thing. It's better to use a Getter / Setter pattern to change the variable even from a child class.

The bug message was just a bit misleading IMO
