### ISSUE TITLE
Add rule to disallow use of Java's Optional

### ISSUE THREAD

**Issue by sebersole** [spotbugs/spotbugs#1068]
Unlike https://sourceforge.net/p/findbugs/feature-requests/297/ I would like to be able to check for any usage of Optional at all.

Optional incurs a performance impact for the overhead of instantiation of a new object - the Optional.  For framework development, this overhead is best avoided.

**Comment by gtoison** [comment]
Hello, sorry for the belated answer
I totally see the motivation for a project such as Hibernate but this will be too opiniated for many users.
An alternative would be using [forbidden-apis](https://github.com/policeman-tools/forbidden-apis) with a custom [signatures file](https://github.com/policeman-tools/forbidden-apis/wiki/SignaturesSyntax)

**Comment by hazendaz** [comment]
Another option is using [modernizer](https://github.com/gaul/modernizer-maven-plugin/releases) which at least will flag invalid usage such as 'get'.  I don't think its overly bad though and agree not something we would suggest here is bad.  Not sure its worth repeating the others either in their various solutions since at least in case of modernizer its a far faster result at compilation than spotbugs would be.  Optional get is after all a poor api design with newer options available to properly overcome that (ie otherwise isPresent must be checked).
