### ISSUE TITLE
Incorrect ModifiedDate (2/1/1980) for files in zip and files in JARs

### ISSUE THREAD

**Issue by blindspeed90** [spotbugs/spotbugs#1134]
Building locally matched the pre-built spotbugs-4.0.3.zip, where all files within it are stamped with 2/1/1980 for the ModifiedDate.  Additionally, JARs within the zip such as asm*.jar and spotbugs*.jar have files within them stamped with 2/1/1980 also.

**Comment by KengoTODA** [comment]
<img width="882" alt="Screen Shot 2020-05-27 at 10 48 11" src="https://user-images.githubusercontent.com/505751/82972415-95671f00-a007-11ea-8cc1-839af1f43d13.png">

**Comment by KengoTODA** [comment]
4.0.4 still has this problem.

**Comment by KengoTODA** [comment]
I found that this is intentional one. We set [preserveFileTimestamps](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/bundling/AbstractArchiveTask.html#setPreserveFileTimestamps-boolean-) property, to [make the build reproducible](https://reproducible-builds.org/).

https://github.com/spotbugs/spotbugs/blob/815b0f743e2601d01fc9f47cc32ff40960c73517/gradle/java.gradle#L12
