### ISSUE TITLE
UnsupportedOperationException after upgrade from 3.1.12 to 4.0.4

### ISSUE THREAD

**Issue by tdzierz** [spotbugs/spotbugs#1161]
Hello,

I have following problem with SpotBugs:

In my project's version 3.1.12 is running fine - we are using it from our Jenkins/Ant scripts.
After changing it to 4.0.4 at some step of our process following exception is thrown in computeBugHistory:

[computeBugHistory] Executing SpotBugs ComputeBugHistoryTask from ant task
[computeBugHistory] Running computeBugHistory...
[computeBugHistory] Starting with d:\\spotbugs-4.0.4/database.xml
[computeBugHistory] Exception in thread "main" java.lang.UnsupportedOperationException
[computeBugHistory]     at java.util.Collections$UnmodifiableCollection.removeIf(Collections.java:1084)
[computeBugHistory]     at edu.umd.cs.findbugs.BugRanker.trimToMaxRank(BugRanker.java:322)
[computeBugHistory]     at edu.umd.cs.findbugs.workflow.Update.discardUnwantedBugs(Update.java:337)
[computeBugHistory]     at edu.umd.cs.findbugs.workflow.Update.doit(Update.java:484)
[computeBugHistory]     at edu.umd.cs.findbugs.workflow.Update.main(Update.java:405)
[computeBugHistory] Java Result: 1

I checked quickly source code of BugRanker and Update classes and it seems there is call to removeIf() method of unmodifiable view of collection - and that lead to UnsupportedOperationException.

Is it bug or some additional steps are needed when upgrade from 3 to 4?

Attaching script and data file (truncated, as simple as possible to reproduce bug).
[spotbugs.zip](https://github.com/spotbugs/spotbugs/files/4758854/spotbugs.zip)

**Comment by KengoTODA** [comment]
I can reproduce this problem even in the version `3.1.12`. Not sure why this reproduces in your environment only with spotbugs `4.0.4`.

* `SortedBugCollection#getCollection()` returns an unmodifiable collection since [`c7ead7e`](https://github.com/spotbugs/spotbugs/commit/c7ead7e64382673b67e5b46a83442c846483230d#diff-f8ef18364a213663b45cd2148619b193R1028) included in v2.0.0.
* `BugRanker.trimToMaxRank()` has 'change to removeIf from Iterator and Iterator.remove' in [`be2447f`](https://github.com/spotbugs/spotbugs/commit/be2447f362d7525314f28fe385e3f9526707e615#diff-14b182164c9922349f56dcefa2ab0174R324) included in 4.0.0_beta2.
* So I expected that `4.0.0_beta2` can reproduce this bug but `4.0.0_beta1` cannot. However, the test 9018f8a36 fails even in both of `4.0.0_beta1` and `3.1.12`.

```
> Task :spotbugs:test

edu.umd.cs.findbugs.BugRankerTest > test FAILED
    java.lang.UnsupportedOperationException
        at java.util.Collections$UnmodifiableCollection$1.remove(Collections.java:1046)
        at edu.umd.cs.findbugs.BugRanker.trimToMaxRank(BugRanker.java:327)
        at edu.umd.cs.findbugs.BugRankerTest.test(BugRankerTest.java:13)
```

**Comment by stoty** [comment]
I've just opened a PR with a possible fix: https://github.com/spotbugs/spotbugs/pull/1284

**Comment by aw-was-here** [comment]
Is there any version that works or is there some other workaround?  I'm seeing this bug in a few different repos now.

**Comment by aajisaka** [comment]
Our project upgraded from Findbugs 3.1.0 (bundled in Ubuntu 20.04) to Spotbugs 4.0.6. After the upgrade, we faced this error.

**Comment by aajisaka** [comment]
Our project executes computeBugHistory with default maxRank (=20). Before
```
        for (Iterator<BugInstance> i = origCollection.getCollection().iterator(); i.hasNext();) {	        origCollection.getCollection().removeIf(b -> BugRanker.findRank(b) > maxRank);
            BugInstance b = i.next();	
            if (BugRanker.findRank(b) > maxRank) {	
                i.remove();	
            }
        }
```
`i.remove()` is not actually called because there are no bugs whose rank is larger than maxRank. That way UnsupportedOperationException does not occur.

After:
```
        origCollection.getCollection().removeIf(b -> BugRanker.findRank(b) > maxRank);
```
`UnmodifiableCollection.removeIf` throws UnsupportedOperationException regardless of the argument.

Possible fixes:
- Skip calling trimToMaxRank if the maxRank is 20. (This is fine for our project, but does not fix this issue when the maxRank < 20)
- Discard unmodifiable collection.
