### ISSUE TITLE
Question about License

### ISSUE THREAD

**Issue by jscancella** [spotbugs/spotbugs#1355]
I am trying to get Spotbugs approved for use at my job. However, the people in charge of approving of the software are concerned about the "copy left license". Can you confirm that by using Spotbugs (and the associated build tool plugins for maven and gradle) that we would not be forced to release our source code that is being evaluated by Spotbugs?

**Comment by iloveeclipse** [comment]
> I am trying to get Spotbugs approved for use at my job. However, the people in charge of approving of the software are concerned about the "copy left license". 

Sincere condolences. I know that people. 

> Can you confirm that by using Spotbugs (and the associated build tool plugins for maven and gradle) that we would not be forced to release our source code that is being evaluated by Spotbugs?

First of all, **no one** here on the project has the authority to confirm anything to your company, because the game the lawyers will play would ignore that completely. I can confirm you everything you like, but no one will accept this at the court I guess.

Question of a usage of a particular software in particular company and particular use case can't be answered in general, and not on the mailing list/forum.

Using internally / redistributing / source modified / not modified / license files are shipped / not shipped / whatever else?
Just look at the github generated header of this page (https://github.com/spotbugs/spotbugs/blob/master/LICENSE) with check marks what is allowed and what not: that alone is not straight forward - there are few limitations and few conditions. If any of them is violated, you can have troubles. Not necessarily from this project, but from someone else (your company competitors) who could be interested to play this game.

At my day job we have a legal department that checks not just the tool but the dependencies and dependencies of dependencies etc if they have some license issues **depending on the concrete software use in the company**.

And finally, back to the concrete question: please simply ask them where in LGPL (https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html) do they see anything about "source code that is **being evaluated** by the Library"? I'm unaware about such clause.

**Comment by hestad** [comment]
Snyk reports spotbugs-annotations' license as a warning:

> ✗ LGPL-2.1 license (new) [Medium Severity][https://snyk.io/vuln/snyk:lic:maven:com.github.spotbugs:spotbugs-annotations:LGPL-2.1] in com.github.spotbugs:spotbugs-annotations@4.1.2
    introduced by com.opentable.components:otj-pg-embedded@0.13.4 > com.github.spotbugs:spotbugs-annotations@4.1.2

Would it be possible to change it or dual license it as e.g. Apache 2.0 / MIT?

(this is not a real issue in my case, since I can just exclude the spotbugs-annotation. I started an issue with otj-pg-embedded as well.)

**Comment by jscancella** [comment]
> 
> 
> Snyk reports spotbugs-annotations' license as a warning:
> 
> > ✗ LGPL-2.1 license (new) [Medium Severity][https://snyk.io/vuln/snyk:lic:maven:com.github.spotbugs:spotbugs-annotations:LGPL-2.1] in com.github.spotbugs:spotbugs-annotations@4.1.2
> > introduced by com.opentable.components:otj-pg-embedded@0.13.4 > com.github.spotbugs:spotbugs-annotations@4.1.2
> 
> Would it be possible to change it or dual license it as e.g. Apache 2.0 / MIT?
> 
> (this is not a real issue in my case, since I can just exclude the spotbugs-annotation. I started an issue with otj-pg-embedded as well.)

You should probably make this a new issue.
