### ISSUE TITLE
[JEP 411] Deprecate `DoInsideDoPrivileged` (`DP_DO_INSIDE_DO_PRIVILEGED` + `DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED`)

### ISSUE THREAD

**Issue by jglick** [spotbugs/spotbugs#1515]
Assuming [JEP 411](https://openjdk.java.net/jeps/411) is accepted, `DoInsideDoPrivileged` will be issuing recommendations to insert API calls which are slated to be officially deprecated and either deleted or made no-ops. Suggest this detector be removed, or disabled by default. https://github.com/spotbugs/spotbugs/blob/43001a94202c4d041880c40224002b2f2b758a95/spotbugs/etc/messages.xml#L2386-L2418

**Comment by pfirmstone** [comment]
Um, please keep this, we don't know what the replacement Security API is yet, my project uses Java Security API's as well as Spotbugs to identify bugs in the build.


People can ignore the issue themselves.

**Comment by jglick** [comment]
> we don't know what the replacement Security API is yet

JEP 411 does not propose a replacement. The whole point is that the concept is outdated and more trouble than it is worth.

To support projects which are remaining on current Java versions indefinitely, it would make sense to merely disable this by default. Or perhaps it could be disabled when the Java target (bytecode) level is 17+ (or whenever JEP 411 lands)?

**Comment by pfirmstone** [comment]
I understand if it's too much trouble for you, however we are still developing for this and all you need to do is use the <excludeFilterFile> and it won't bother you again.   The impact of missing this bug matters to us.

A Principle of Least Privilege (POLP) authentication layer is not an outdated concept.   We are experiencing increasing demand.  The way that OpenJDK documents the way to use Security policy files is an outdated concept however, they only have trust completely or not at all, so that trusted code is granted AllPermission and they try and sandbox untrusted code, so it doesn't constrain their trusted code at all.   We don't allow untrusted code into the system, but we limit trusted code (and roles) to only what they need to do, if we have a bug in our software, something that's not obvious, POLP limits the damage an attacker can do.

We also have highly scalable security manager, policy implementations, and tools to generate POLP policy files, the only argument in JEP 411 that applies to us is the maintenance burden.  All other arguments are based on the Java implementations which are crap and old outdated ideas like trusted code with AllPermission.

POLP policy files only grant permissions which are absolutely necessary to perform intended functions.  Nothing else is allowed, so this has a big benefit to security.

Security is very important, SpotBugs is security focused.   I would definitely prefer and be grateful if you just modified your excludeFilterFile accordingly.

**Comment by pfirmstone** [comment]
Maybe just mention in documentation that SecurityManager is deprecated in Java 17.

**Comment by jglick** [comment]
@pfirmstone this is not the right place to give feedback on JEP 411 itself. The point is that, assuming the proposal is accepted (and it is currently targeted for Java 17), SpotBugs will be issuing a warning advising developers to begin calling a method on a class which has already been deprecated for removal. That has a real cost—developers are less likely to run SpotBugs at all if it issues irrelevant warnings that require special action to suppress—and the cost would be paid by all applications using newer versions of Java, as well as the vast majority of applications remaining compatible with older versions, whenever they happened to work with `ClassLoader`s. Therefore the rule should be disabled by default at least when running on 17+ (arguably unconditionally), leaving it opt-in for the small set of applications which use this system.

**Comment by pfirmstone** [comment]
If 30 seconds to comment out one bug is going to drive someone away, then they probably would have given up long before the came across this bug and they probably aren't concerned about security anyway.

The developer is supposed to read the bug description and determine whether the bug applies to them, there are lots of bugs like that.   No one is using Java 17 yet, it will be released in September, even then the adoption rate will be low for a few years.

The cost of missing the bug is greater than commenting it out for someone whose code it doesn't apply.   The most sensible thing to do is add it to the code comment, I'm quite willing to submit a pull request to that effect, if the authors decide that's the solution, otherwise, you can submit a pull request to detect Java 17+

We won't be migrating past Java 17, in our assessments the platform will be significantly less secure and there will be many more large customers who will continue using SM for at least 10 years and possibly longer.

We are investigating what to do about an authorization layer for later versions of Java, however this is very recent news and we are still trying to come to terms with the impact.

**Comment by vitalyd** [comment]
FWIW, I agree with @jglick that this warning should be (at a minimum) disabled when targeting jdk 17+.  It doesn’t make sense to suggest using a deprecated-for-removal API.

**Comment by pfirmstone** [comment]
Can we do that for the Java version when SM becomes degraded? And leave 
it in place for earlier Java releases?   OpenJDK has advised that a new 
JEP will be released for degradation or removal of SM, can we not wait 
for that?

While the API exists, the security bug may still be a threat, once the 
API is removed, then the check is no longer relevant on that version.

We've now established that we are unable to upgrade our software to 
later versions of Java once SM becomes degraded, it hasn't yet, based on 
discussions on OpenJDK I think we can still re-enable it on Java 18, our 
software requires an authorization layer.  In our software not only is 
SM infrastructure used to obtain credentials for TLS connections 
(replacement functionality doesn't exist), but it's also used to prevent 
parsing of untrusted data.   Remove it and not only will our TLS 
connections stop working, but our software has no defenses against 
parsing potentially malicious data.

Our software is designed around the authorization layer in the Java 
platform, it's not possible for a third party library to implement this 
functionality, discussions on OpenJDK mailing lists have now established 
that the suggested work-around's aren't practical due.  We also use it 
as part of our security auditing process, see my link below for further 
clarifications.

We are still supporting the latest Java version while it's possible to 
do so, we will also be testing on previous LTS versions.

Don't believe everything you read on JEP 411, SM is not useless software 
that nobody uses, OpenJDK just don't have enough maintenance resources 
to continue supporting it.   For us, JEP 411 definitely makes Java less 
secure, anything suggesting otherwise is just spin.

In case you're wondering how we use Spotbugs and SM for auditing 
purposes, see my post here:

https://mail.openjdk.java.net/pipermail/security-dev/2021-July/026907.html

Thanks,

Peter.

**Comment by jglick** [comment]
If a handful of applications continue to use `SecurityManager`-related APIs, despite being `@Deprecated`, with a Java 17+ target, their maintainers already have a straightforward workaround: use an older version of SpotBugs. (Or latest SpotBugs, _plus_ an older release with this one detector enabled.) It does not make sense to default the detector to enabled and force far more people to spend an hour Googling around for how to disable it or sprinkling `@SuppressFBWarnings` all over.

**Comment by pfirmstone** [comment]
Hi Jesse,

You've made this statement like you're making the decision, but I 
checked, you're not one of the developers and must be a user like me.

I would also argue that if you're not using SM, then you're also not 
using doPrivileged, in which case, you will never see this bug reported 
anyway.

I think that hour spent would be a valuable investment, as there are 
other bugs that will need to be reviewed.  I recommend using a file 
rather than annotations, so you can keep all your bugs in one place. :)

In your Maven pom, add the following:

<reporting>
     <plugins>
        <plugin>
                 <groupId>com.github.spotbugs</groupId>
<artifactId>spotbugs-maven-plugin</artifactId>
                 <configuration>
<excludeFilterFile>spotbugs-exclude.xml</excludeFilterFile>
                 </configuration>
          </plugin>
     </plugins>
</reporting>

then in your spotbugs-exclude.xml file, any bugs you've reviewed, that 
don't need to be changed:

<FindBugsFilter>

     <Match>
         
         <Class 
name="org.apache.river.api.net.RFC3986URLClassLoader$UriCodeSource"/>
         <Bug pattern="SE_BAD_FIELD"/>
     </Match>

</FindBugsFilter>

I've stated my use case, if we adopted your approach, it's likely this 
bug (or others if using an older version of SpotBugs) will be missed, 
I'd prefer a false positive, so I'll leave it to the SpotBugs developers 
to decide the outcome and respect the decision they make.

Regards,

Peter.

**Comment by jglick** [comment]
> you're not one of the developers and must be a user like me

Correct, and I apologize if my wording implied otherwise. I am just offering an opinion as a developer in an org that runs SpotBugs on hundreds of repositories. We do use an exclusion file sometimes but generally hope that the default detectors at a given severity level correspond well enough to meaningful issues that it is practical to use annotations (with `justification`) for the exceptions. At least until #1601 that has worked—the rate of false positives is modest enough that developers do not get frustrated and turn the tool off altogether.

> if you're not using SM, then you're also not using doPrivileged, in which case, you will never see this bug reported anyway

`DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED` is reported on code which makes no reference to `SecurityManager`. That is the point.

**Comment by pfirmstone** [comment]
No worries.

**Comment by ArloL** [comment]
Just wanted to ask if there are any reasons with JDK 17+21 being shipped including doPrivileged being deprecated and marked forRemoval to still mark this as a bug by default? I am aware that I can exclude it myself - that's what I did - just wanted to ask if I can stop doing that at some point? Just curious what the strategy is for stuff like that :)

**Comment by pfirmstone** [comment]
Just thought I'd mention that we're still supporting multiple versions of Java where the cost of this bug, should it be missed is significant.    Also, I'd like to thank the SpotBugs team for helping us find many bugs over the years.

https://github.com/pfirmstone/jdk-with-authorization
