### ISSUE TITLE
Annotating both @Inject and @Nonnull doesn't work 

### ISSUE THREAD

**Issue by nicolaichuk** [spotbugs/spotbugs#167]
please fix this issue

https://sourceforge.net/p/findbugs/bugs/1479/

it still reproduce with spotbugs 3.1.0-RC1

**Comment by KengoTODA** [comment]
I think we can say it's expected behaviour. Even though field is annotated with `@Inject`, it is possible to generate instance without support from DI container, so it can be null.

I recommend you to use constructor-injection instead of field-injection, then SpotBugs can show intuitive report for you. It is also good practice for DI: http://stackoverflow.com/a/39892204/814928

If you still prefer field injection to keep your code readable, I personally recommend https://projectlombok.org/ to have a try.

**Comment by cornzy** [comment]
@KengoTODA we just move from eclipse null checker (wich was quite annoying) to spotbugs null checks. So far it was quite useful. But this issue is quite painful. I would not say that there is very much field injection but there are some and we do not want to transform every field injection to constructor injection (although it might be better in most situation).

Of course there is the posibility that an object is instantiated without DI although it is annotated with @Inject. But in this case there went something other completely wrong. I would never use the @Inject annotation for fields of objects which is not injected!

Whats about making it optional to ignore not initialized fields when they are marked with @Inject?

**Comment by hd42** [comment]
Should InitializeNonnullFieldsInConstructor maybe use something like UnreadFields.isInjectionAttribute(String) to catch this?
