### ISSUE TITLE
ant plugin does not accept "userPrefs"

### ISSUE THREAD

**Issue by krisan6** [spotbugs/spotbugs#185]
According to the javadoc in spotbugs-ant/src/main/java/edu/umd/cs/findbugs/anttask/FindBugsTask.java, the ant plugin should accept:
   `userPrefs (user preferences filename)`

Adding it inside the spotbugs task gives this error:
`spotbugs doesn't support the "userPrefs" attribute`

The same issue exists in the findbugs ant plugin. I don't know who is supposed to call the setter for the field so I don't know how to fix it myself.
The "-userPrefs" flag works when using the textui, so there's probably just some simple argument check missing for the ant plugin

**Comment by KengoTODA** [comment]
According to [this manual](http://findbugs.sourceforge.net/manual/anttask.html), we should use `userPreferencesFile` attribute instead of `userPrefs`. `userPrefs` is [valid option for text UI](http://findbugs.sourceforge.net/manual/running.html#commandLineOptions).

I will fix javadoc in another PR.

**Comment by krisan6** [comment]
I can't believe I didn't notice that the manual showed the correct usage :)
Thanks for fixing the javadoc so no one else makes the same silly mistake as me.
