### ISSUE TITLE
Spotbugs 4.5.x does not generate HTML report

### ISSUE THREAD

**Issue by AchalKansal** [spotbugs/spotbugs#1853]
Hi team,

I am using spot bugs 4.5.0 jar to generate the HTML report but am unable to do so. It generates XML reports though.

The steps which are being followed
1. 
```
<plugin>
  <groupId>com.github.spotbugs</groupId>
  <artifactId>spotbugs-maven-plugin</artifactId>
  <version>4.5.0.0</version>
  <configuration>
	  <effort>Max</effort>
	  <threshold>Low</threshold>
	  <maxHeap>2048</maxHeap>
	  <xmlOutput>false</xmlOutput>
	  <!-- Optional directory to put spotbugs xdoc xml report -->
	  <xmlOutputDirectory>target/</xmlOutputDirectory>
  </configuration>
  </plugin>
```

2. Maven command : `mvn spotbugs:spotbugs -Dhtml:spotbugs.html`

**Comment by KengoTODA** [comment]
Hi, are you using the Windows platform? I guess it's related to #1809 or #1827.

**Comment by AchalKansal** [comment]
@KengoTODA : yes I am using Windows platform.

**Comment by AchalKansal** [comment]
Any updates on this?

**Comment by KengoTODA** [comment]
no update for now.

**Comment by geruiz** [comment]
I have found the same issue in Spotbugs version 4.7.1.1.  Is there a workaround available?

**Comment by wojciechGaudnik** [comment]
4.7.2.1 the same.

**Comment by hazendaz** [comment]
Hi, you are using maven plugin, it needs to set the report flag for that to occur.  Passing environment variables outside of that are not going to do anything as you have found.

See https://github.com/spotbugs/spotbugs-maven-plugin/blob/master/src/it/html-report/pom.xml for example.  

Closing ticket as I think this was a configuration issue.  If not, please open ticket over on the maven plugin rather than directly on spotbugs.  Thanks.
