### ISSUE TITLE
"Can't find ClassInfo" when looking at dependency

### ISSUE THREAD

**Issue by turturel** [spotbugs/spotbugs#2144]
(original issue [here](https://github.com/spotbugs/sonar-findbugs/issues/630))

We have a Maven project which produces a war and has Liquibase as a dependency. We scan this project with Sonar's sonar-findbugs plugin and it was working fine until we updated the Liquibase dependency to 4.9.1 (from an older version) - after that we started getting **_java.util.concurrent.ExecutionException: java.lang.AssertionError: Can't find ClassInfo for liquibase\package-info_** 

I was able to reproduce this issue also with SpotBugs GUI and spotbugs-maven-plugin.

Attached a very small Maven project which you can use to reproduce the issue - [spotbugs-crash-sample.zip](https://github.com/spotbugs/spotbugs/files/9373837/spotbugs-crash-sample.zip) Just unzip it and run **_mvn compile com.github.spotbugs:spotbugs-maven-plugin:4.7.1.1:spotbugs_**

What doesn't SpotBugs like about liquibase-core-4.9.1.jar\liquibase\package-info.class?

Maven 3.8.4
Java 1.8.0_321
SpotBugs 4.7.1

**Comment by turturel** [comment]
In case anyone cares, this is still happening in 4.8.2 :)

**Comment by ThrawnCA** [comment]
I think SpotBugs should ignore `package-info.java`

**Comment by hazendaz** [comment]
@turturel The example you have provided does not crash as noted.  Sorry this is going to be long...

I've ran with maven 3.8.4 as well as 3.8.8 (last in that series) and finally maven 3.9.6.

I used the same run line you suggested making sure to 'clean' between to be sure all executions were running.  I was able to use java 8, 11, and 17.  If I upgrade to supported versions of spotbugs (4.8.2), then I can also run your code with java 21 and java 22.

Now its probably a critical thing you state, you are working with sonar and it happens with sonar yet you did not explain that here.  You did on your other thread with stack trace, noted in here as used but then stated you only needed to run maven to make this happen.

So I think you have not provided enough information here to help at this point since it does work.

Package info files are nothing new.  I haven't written a project without then in a decade and never seen such a problem.  In fact, if you look, the maven plugin has them too as I'd think most OSS does.  But beyond that, the maven compiler plugin started silently forcing them to exist some time ago (can be disabled but that is the default).  From my experience that only ever surfaced as a problem when it came to java 9+ with javadocs using automatic module naming (again spotbugs maven plugin does that too) which was a long standing defect from maven they just finally relented on (too eager for modular!).  But your case seems to imply you are just java 8 (not newer jdk build either) and there just isn't enough here to reproduce the issue.  I checked liquibase and they do not consistently use package-info.java as they should so the compiler is likely adding them.  Their build is also unusual in that their core package has nothing in it yet that is where the code lives when all said and done so it only has the few package info files they have elsewhere within it.

Have you retried your issue?  Can you share your stack trace (new one)?  Can you tell us every single software version used including other plugins?  Without a stack, its not even clear it was related to spotbugs.

You may also want to consider a few things even on these small examples because there are clear setup issues.  First you didn't provide a war plugin version so maven produces warnings.  Second your XSD is the old maven one from more than a decade ago that is redirecting (just open it in a browser and use the fixed result).  Also you have colons in the name block that does affect some IDEs in bad ways (MyEclipse for example - at least years ago).  And finally more important here, still using package.html files.  The package-info.java files replaced those.  While none of that mattered here, I'm just pointing it out because if I can see that on such a small set of files, I would be more concerned where you really are seeing this and possibly missing a lot about java that has changed over the years that could be what is affecting your situation.

And it should also be noted, every version you have listed here as it stands is out of support.  Yes they may have been current at that time but just pointing that out as a referesh should note that all other pieces are newer by now and facing same issue for you, not just spotbugs.  I'm familiar enough with liquibase, we have a super pom that supports a pom specifically for our liquibase implementation making it 2 layers before database logic teams provide, we use sonar, use use latest everything, and we have not seen any such issue.

But on a gut guess here, are you potentially overlapping either their packages or your own, using OSGI or really using a newer jdk where modular is trying to come into play?  More important here from looking at liquibase is that they do not follow proper packaging convention at all.  So it starts as 'liquibase'.  Usually it would be something like 'org.liquibase.xxx' so that it is not going to cause collisions with unsuspecting users that might just name a folder also 'liquibase' and stick stuff in there.  If any of that is even remotely true here, that would certainly be your root issue.

Again, sorry so long but took a good deal of time to review all this and just wanted to express it all in hopes it helps at the least.  I'm willing to look again if you can get a working exactly that does fail.  Thanks.

**Comment by turturel** [comment]
@hazendaz - thank you so much for looking into this!

After updating the liquibase-core dependency to a more recent version, the issue no longer occurs.
