### ISSUE TITLE
Separate unit from integration tests

### ISSUE THREAD

**Issue by sewe** [spotbugs/spotbugs#240]
Currently, [`spotbugs/src/test/java`](https://github.com/spotbugs/spotbugs/tree/5555d53c5b8e42048fa91da64cc27e57f08651e2/spotbugs/src/test/java/edu/umd/cs/findbugs) contains just two unit tests (one of which, [`PackageDependenciesTest`](https://github.com/spotbugs/spotbugs/blob/5555d53c5b8e42048fa91da64cc27e57f08651e2/spotbugs/src/test/java/edu/umd/cs/findbugs/architecture/PackageDependenciesTest.java), doesn’t even test a unit but looks for package cycles). Instead, most of the **unit** tests are located in the `spotbugs-tests` project, together with the **integration** tests. This is confusing.

We should hence move all tests that 1) test a single, well-defined unit and 2) neither run SpotBugs itself nor need access to test data from `spotbugsTestCases` to `spotbugs/src/test/java`, where convention expects them.

**Comment by jsotuyod** [comment]
This is mostly due to cyclic dependencies between spotbugs, test-harness and unit tests. It was a hack to get it out of the way before going for a major refactor. As we created that `spotbugs-tests` module we discussed splitting spotbugs into a `spotbugs-core`, and `spotbugs-detectors` and have dependencies between modules as:

`test-harness` depends on `spotbugs-core` as `compile`
`spotbugs-detectors` depends on `spotbugs-core` as `compile` and `test-harness` as `test`
`spotbugs-core` is stand-alone

Each module can then have it's own unit tests, in particular, most of what is currently under `spotbugs-tests` would be moved to `spotbugs-detectors/src/test/java`

**Comment by sewe** [comment]
@jsotuyod I totally agree that `spotbugs-core` and `spotbugs-detectors` is the way to go (I even opened #193 for it). But such a change is not for version 3.1.0, I’am afraid, as much as I would like it.

The being said, pull request #241 IMHO already improves the situation, as it moves the simple unit tests out of the way.

**Comment by sewe** [comment]
Closed with pull request #241.
