### ISSUE TITLE
Gradle plugin 1.1 fails to run task

### ISSUE THREAD

**Issue by ben-manes** [spotbugs/spotbugs#250]
The 1.0 release runs fine, but when updated the task fails.

```
* What went wrong:
Execution failed for task ':caffeine:findbugsMain'.
> Unable to infer the version of FindBugs from currently specified FindBugs classpath: [spotbugs-3.1.0-RC3.jar, asm-debug-all-6.0_ALPHA.jar, jcip-annotations-1.0.jar, dom4j-1.6.1.jar, commons-lang-2.6.jar, jaxen-1.1.6.jar, jdepend-2.9.1.jar, jFormatString-3.0.0.jar, spotbugs-annotations-3.1.0-RC3.jar, xml-apis-1.0.b2.jar, jsr305-3.0.1.jar]
```

**Comment by iloveeclipse** [comment]
This should be fixed in head, we just need someone to release the fixed version.

**Comment by ben-manes** [comment]
Thanks!

**Comment by iloveeclipse** [comment]
@KengoTODA, @jsotuyod : who did the last gradle plugin release? Is there some "how to" available?

**Comment by jsotuyod** [comment]
@iloveeclipse it's been some time since I last released, I don't know if @KengoTODA did it in the meantime.

Unfortunately the Gradle plugin portal is quite new, and has no real support for teams. We have to share the same API key to release, and it has to remain private so it has to be shared and stored outside of git. I'll gladly share it along a small how-to on how to release the plugin with any member willing to do it.

In the meantime I'm willing to make a new release if it's ready. Are there any pending issues affecting the plugin to refrain from performing a 1.2 release?

**Comment by ben-manes** [comment]
You could have Travis release on when a tag is created and store the keys their as a hidden environmental variable. This was a nifty trick that a contributor to gradle-versions-plugin added:

```yaml
deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true
```

**Comment by iloveeclipse** [comment]
I think we are ready for RC4.

**Comment by koppor** [comment]
I would like to try out SpotBugs in a my Gradle Project [JabRef](https://github.com/JabRef/jabref/) and a missing release is kind of a blocker for me. Is it possible to release an update of the plugin. I think, a release of a new version of SpotBugs ist not required, is it?

Plugin version 1.0 also does not work, because of https://github.com/spotbugs/spotbugs/issues/1.

When checking https://github.com/spotbugs/spotbugs/milestone/1, I think, a full release of 3.10 is not too far away. 🎉
