### ISSUE TITLE
edu.umd.cs.findbugs.classfile.ResourceNotFoundException: Resource not found: java/lang/Object.class at edu.umd.cs.findbugs.classfile.impl.ClassPathImpl.lookupResource(ClassPathImpl.java:162)

### ISSUE THREAD

**Issue by elisabetnarda** [spotbugs/spotbugs#2683]
i was trying to recompile using LIFT

**Comment by JuditKnoll** [comment]
From the title, it seems like https://github.com/spotbugs/spotbugs/issues/1255. If the problem is the same, then the problem is in the [Intellij SpotBugs plugin](https://github.com/JetBrains/spotbugs-intellij-plugin). Can you please report the issue there?
If it's not, can you please provide additional information? We can't replicate the problem from the information you provided.
