### ISSUE TITLE
CT_CONSTRUCTOR_THROW: false positives constructing lambdas

### ISSUE THREAD

**Issue by pburka** [spotbugs/spotbugs#2695]
In spotbugs 4.8.1 and Java 17.0.6, the `CT_CONSTRUCTOR_THROW` bug is incorrectly detected if the constructor creates a lambda which could throw an exception if used, even if the lambda is not used in the constructor.

Test case:

```
// CT_CONSTRUCTOR_THROW test case

import java.util.function.*;

public class Foo {
    Supplier<String> s;

    public Foo() {
        s = Foo::supplier;
    }

    private static String supplier() {
        //return "Foo";
        throw new IllegalStateException();
    }
}
```

This reports:

```
M B CT_CONSTRUCTOR_THROW CT: Exception thrown in class Foo at new Foo() will leave the constructor. The object under construction remains partially initialized and may be vulnerable to Finalizer attacks.  At Foo.java:[line 9]
M P URF_UNREAD_FIELD UrF: Unread field: Foo.s  At Foo.java:[line 9]
```

The unread field detection is correct; the constructor throws detection is not.

If we change the test case by commenting out the `throw` and uncommenting the `return`, the `CT_CONSTRUCTOR_THROW` bug is no longer reported.

**Comment by big-andy-coates** [comment]
Given that finalizer methods are pretty much a dead pattern in Java, is there not an argument that `CT_CONSTRUCTOR_THROW` should be off by default?

**Comment by JuditKnoll** [comment]
@pburka Thank you for raising this FP. I will look into this issue and propose a solution soon.

@big-andy-coates This detector draws attention to a vulnerability to finalizer attacks, which can be solved by several ways, not just by defining a finalizer method, but also declaring the class final, defining the constructor as private, removing the exception throw from the constructor (or from the called method), or wrapping the exception throw and logging the exception properly inside the constructor. The vulnerability still exists and can be exploited. So IMO just because one of the ways it can be solved is a dead pattern, it doesn't means that the problem doesn't exist.

**Comment by big-andy-coates** [comment]
It seems adding a final, empty finalise method avoids the fault.

I wonder if a better implementation would be to find classes with non-empty finaliser and only warn of any of its constructors throw?

This would avoid a lot of noise and avoid missing issues due to people disabling a noisy check.

**Comment by JuditKnoll** [comment]
> It seems adding a final, empty finalise method avoids the fault.
> 
> I wonder if a better implementation would be to find classes with non-empty finaliser and only warn of any of its constructors throw?
> 
> This would avoid a lot of noise and avoid missing issues due to people disabling a noisy check.

Yes, an empty final `finalize()` does solve the problem, since that's a compliant solution to the problem. In fact, defining any final `finalize()` prevents the finalizer attack, it doesn't have to be empty. I think the proposed solution would miss a lot of valid hits, causing false negatives, when those could be easily found. 
If you find any false positive like the one this issue is about, or some particularly noisy situation and can share a minimal verifiable example, please feel free to share it.
