### ISSUE TITLE
Remove maven/bcel hack from spotbugs.jar

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#327]
Follow up on #326 : currently our `spotbugs.jar` contains not just our code but also content from `spotbugs-annotations.jar` and `BCEL.jar`. At least the later one is included because BCEL still haven't released an updated library (see #89). I still have no clue why we include `spotbugs-annotations.jar` too (because of maven - but I see the http://repo1.maven.org/maven2/com/github/spotbugs/spotbugs-annotations/?).

Releasing  `spotbugs.jar` containing other classes is at least problematic, because the classpath of dependent libraries could be affected in surprising ways, and class loading issues could be very hard to debug/understand.

One idea coming to my mind is to customize `uploadArchives` task which is used to release our libraries to maven central (if I got it right). There, and only there, use a *merged* jar file.

**Comment by iloveeclipse** [comment]
Probably the best solution would be to have spotbugs-bcel subproject, same as spotbugs-annotations etc and just move there this custom BCEL.jar file which is today checked under spotbugs/spotbugs/lib. 

This spotbugs-bcel.jar could be simply published to maven and consumed as any other of our dependencies.

WDYT?

**Comment by sewe** [comment]
> Probably the best solution would be to have spotbugs-bcel subproject, same as spotbugs-annotations etc and just move there this custom BCEL.jar file which is today checked under spotbugs/spotbugs/lib.

@iloveeclipse IMHO, the best solution would be to push the BCEL project to cut a new release (possibly assisting them, in case they need help testing stuff). What you are suggesting is forking BCEL instead, which I wouldn’t even call the second-best solution…

**Comment by iloveeclipse** [comment]
Unfortunately we can't always have only "best" solutions :-(

I have hard worked to get BCEL 6.0 released, and this took a year or so. I honestly don't have time/interest to repeat this experience again.

I'm not asking for a fork, I just want to have intermediate snapshot of their work released with a custom maven coordinates, so that we can refer to this in our maven pom. If I understand it right, all maven dependencies a project has must be on maven central, so I see no other clean solution.

**Comment by sewe** [comment]
> I have hard worked to get BCEL 6.0 released, and this took a year or so. I honestly don't have time/interest to repeat this experience again.

I appreciate the effort you’ve put into this. Could you share a bit of info on what was required/why it took so long? I might be willing to help out.

> I'm not asking for a fork, I just want to have intermediate snapshot of their work released with a custom maven coordinates, so that we can refer to this in our maven pom. If I understand it right, all maven dependencies a project has must be on maven central, so I see no other clean solution.

There are two options:

1. Depend in the (generate) POM on BCEL. Then you are right; all our POM dependencies must also be on Central.
2. We “shade” the dependency into our JAR and do **not** declare a dependency on BCEL.

Personally, I don’t think option 2 is too bad, as I wouldn’t want other people picking our BCEL 6.1 snapshot from Central (because they are also tired of waiting for a release) and our `spotbugs-bcel` becoming a de-facto fork.

At any rate, the one thing we should **not** do is include BCEL in our JAR **and** still state a dependency on it in our POM. That’s why, for example, the `maven-shade-plugin` has a [`createDependencyReducedPom` option](https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#createDependencyReducedPom).

**Comment by iloveeclipse** [comment]
> Could you share a bit of info on what was required/why it took so long? I might be willing to help out.

OK, it was may be not a year, but it felt like a year for me.

The problem with BCEL was that they had no maintainer (or no *active* one). Then, at the moment I wanted to use their new stuff I realized that they broke every API they could just because it was cool and they could do it. Then I had to convince them to release the library which does not break everyone on the earth. Then It was really hard to get any feedback, and to get someone to work on deploying the library. Additionally, they use apache commons mailing list where you get tons of unrelated spam if you want only to follow BCEL. I've asked them to change this, but they didn't want to change that, however, so I switched myself off after BCEL 6.0 was released. It was really bad experience.

But meanwhile I see they are on github (https://github.com/apache/commons-bcel), so could it be they just need more "pressure" to move forward.

See 
* https://issues.apache.org/jira/browse/BCEL-222
* http://mail-archives.apache.org/mod_mbox/commons-dev/201606.mbox/%3C1484519.iNUkTTbiIx%40pinguin%3E
* https://github.com/findbugsproject/findbugs/issues/106
 * http://mail-archives.apache.org/mod_mbox/commons-dev/201607.mbox/<CAB917RLaOdz3O-QDkzFDAsUzKguxvUqXXOd6Pb=uvYgeSfMDRw@mail.gmail.com>

**Comment by hazendaz** [comment]
We were using the findings variation within mybatis for sometime last year.  My opinion is to put pressure on apache to release more often but that seems like a lost cause most of the time.  I don't necessarily like forking and releasing because it's not very community friendly but I doubt apache would really be more community reactive to change.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by iloveeclipse** [comment]
Thanks to #388 this is fixed now.
