### ISSUE TITLE
Path separation problem

### ISSUE THREAD

**Issue by VelinYordanov** [spotbugs/spotbugs#479]
[INFO] --- static-code-analysis:0.3.0:findbugs (default) @ org.eclipse.smarthome.ui ---
    [INFO] Adding dependency to static-code-analysis:0.3.0
    [INFO] Adding dependency to bug-pattern:1.2.4
    [INFO] Adding dependency to spotbugs:3.1.0-RC3
    [INFO] Fork Value is false
    [java] JVM args ignored when same JVM is used.
    [java] The following errors occurred during analysis:
    [java] File from auxiliary classpath not found: filesystem:C:\projects\smarthome\bundles\ui\org.eclipse.smarthome.ui\lib\xchart-2.6.1.jarC:\Users\Achim.m2\repository\p2\osgi\bundle\org.eclipse.jdt.annotation\2.1.100.v20170511-1408\org.eclipse.jdt.annotation-2.1.100.v20170511-1408.jar
    [java] java.io.FileNotFoundException: File C:\projects\smarthome\bundles\ui\org.eclipse.smarthome.ui\lib\xchart-2.6.1.jarC:\Users\Achim.m2\repository\p2\osgi\bundle\org.eclipse.jdt.annotation\2.1.100.v20170511-1408\org.eclipse.jdt.annotation-2.1.100.v20170511-1408.jar doesn't exist
    [java] At edu.umd.cs.findbugs.classfile.impl.ClassFactory.createFilesystemCodeBase(ClassFactory.java:111)
    [java] At edu.umd.cs.findbugs.classfile.impl.FilesystemCodeBaseLocator.openCodeBase(FilesystemCodeBaseLocator.java:77)
    [java] At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.processWorkList(ClassPathBuilder.java:628)
    [java] At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.build(ClassPathBuilder.java:230)
    [java] At edu.umd.cs.findbugs.FindBugs2.buildClassPath(FindBugs2.java:677)
    [java] At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:218)
    [java] At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
    [java] At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
    [java] At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [java] At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [java] At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [java] At java.lang.reflect.Method.invoke(Method.java:498)
    [java] At org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:221)
    [java] At java.lang.Thread.run(Thread.java:748)
    [INFO] Done FindBugs Analysis....

    art-2.6.1.jarC:\Users\

Seems like there is a problem with path separation. Can you provide any assistance?
See eclipse/smarthome#4457

**Comment by iloveeclipse** [comment]
Velin: please provide steps to reproduce and please try to use the final 3.1.0 version.

**Comment by VelinYordanov** [comment]
@iloveeclipse I tried using the 3.1.0 version unfortunately it didn't solve the problem.
I attached a zip file with code example. If you run `mvn clean install` in the root folder you should be able to reproduce the problem.

[example.zip](https://github.com/spotbugs/spotbugs/files/1441582/example.zip)

**Comment by Bananeweizen** [comment]
We see exactly the same issue here. This happens with spotbugs 3.1.0 and spotbugs-maven 3.1.0-RC7. This is a regression compared to Findbugs and findbugs-maven (and I'm not sure this is a spotbugs issue, I rather think of a spotbugs-maven issue).

Im convinced the error is in concatenating the auxiliary classpath. This part of the output is still correct, in that we see "adding to auxclasspath" for a list of paths:
>[DEBUG]   Adding to AuxClasspath ->C:\m2repo\p2\osgi\bundle\org.hamcrest.core\1.3.0.v201303031735\org.hamcrest.core-1.3.0.v201303031735.jar
00:02:38 [DEBUG]   Adding to AuxClasspath ->C:\m2repo\p2\osgi\bundle\org.w3c.dom.smil\1.0.1.v200903091627\org.w3c.dom.smil-1.0.1.v200903091627.jar
...
00:02:38 [DEBUG]   Adding to AuxClasspath ->C:\libs\cpsuite-1.2.6.jar

but directly afterwards in the debug output the concatenated string is wrong. It starts with a semicolon to much, and misses a semicolon in the middle of the string. The missing semicolon in the middle (look for "jarC:\" in the text below to exactly locate it) later causes the attempt to locate a path that is actually the concatenation of 2 paths.

> AuxClasspath is ->;C:\m2repo\p2\osgi\bundle\ch.qos.logback.classic\1.1.2.v20160208-0839\ch.qos.logback.classic-1.1.2.v20160208-0839.jar;
...
C:\libs\cpsuite-1.2.6.jarC:\m2repo\p2\osgi\bundle\org.eclipselabs.xtext.utils.unittesting\0.9.3.201204261440\org.eclipselabs.xtext.utils.unittesting-0.9.3.201204261440.jar;

I guess the logic for adding the semicolon as separator has an off by one error, since the semicolon is missing before the last entry that is added to the auxclasspath.

**Comment by Bananeweizen** [comment]
@sewe I think this might be related to your patch https://github.com/gleclaire/findbugs-maven-plugin/pull/57/files. The loop that you removed created an auxclasspath like "path1;path2;path3" and afterwards the very first next step was adding another ";" in https://github.com/gleclaire/findbugs-maven-plugin/pull/57/files#diff-939d53bfea6263d70d31b8a28b00f779L974 to continue adding new entries.

Now that you removed the loop, adding that same semicolon as the very first step in https://github.com/spotbugs/spotbugs-maven-plugin/blob/spotbugs/src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy#L940 is probably no longer correct.

**Comment by sewe** [comment]
@Bananeweizen Thank you for the detailed analysis. Can I ask you for a pull request?

**Comment by Bananeweizen** [comment]
@sewe I have done that analysis using Google and the browser only. I don't really feel confident in that code base to actually propose a change. E.g. my gut feeling says to simply delete the line adding the semicolon, but I can't really test this in any useful way.

**Comment by sewe** [comment]
@Bananeweizen OK, fair enough. As @VelinYordanov provided an example project, I’ll try to fix and test this over the weekend, then.

**Comment by hazendaz** [comment]
@Bananeweizen @sewe Given the maven plugin is entirely based on top of the findbugs version and this issue seems to me to have been created back in July against find bugs plugin, would it be correct in my assumption that we need the same fix back on the findbugs maven project as well?  Since I've been mostly just rebasing it to fix various issues in the original along with others help, I'm not seeing how this showed up here but also haven't looked deep enough.

**Comment by Bananeweizen** [comment]
@hazendaz That seems quite reasonable to me. But I'm only a user of the plugin, so @sewe can probably judge this better.

**Comment by hazendaz** [comment]
@gleclaire There was a fix on spotbugs-maven-plugin relatated to this.  Can you take a look and see if this is something you need on your version?  I sort of think that it is.

**Comment by gleclaire** [comment]
I will have a look to see if it is needed and will add if so.
