### ISSUE TITLE
False positive when dogfooding UC_USELESS_CONDITION?

### ISSUE THREAD

**Issue by ThrawnCA** [spotbugs/spotbugs#86]
`UC_USELESS_CONDITION` fires on `DontIgnoreResultOfPutIfAbsent` line 260, apparently thinking that the value of `isIgnored` has already been determined. However, as best I can tell, this is incorrect. The condition at line 245 is an inclusive OR ||, so if `countOtherCalls` was true, then there is no telling whether `isIgnored` is true or false at this point.

**Comment by jsotuyod** [comment]
Actually, the report is right. `countOtherCalls` is [guaranteed to be false](https://github.com/spotbugs/spotbugs/blob/master/findbugs/src/main/java/edu/umd/cs/findbugs/detect/DontIgnoreResultOfPutIfAbsent.java#L78)

So if you get into that if, it's only because `isIgnored` is true, and therefore, the conditional is actually useless.

I'd suggest killing `countOtherCalls`, simplifying that code to solve the issue, and remove the commented out code in that detector.

**Comment by ThrawnCA** [comment]
Hmm. You're right, but it's pretty odd that it's doing that. Maybe `countOtherCalls` was meant to be a debugging flag or something, toggled at compile time? Note that its other, commented-out usages are in conjunction with the also-commented-out `testingEnabled` flag.

**Comment by jsotuyod** [comment]
Yes, there are plenty of such flags in the code. Undocumented, unused, and legacy (if you check a blame / history you can probably trace those back over a decade). Most of the messy code is either useless, or Findbugs trying to be super smart about the priority to assign an issue (and usually just failing, as recently seen with lambdas). Cleanse it with fire, no one will miss it, and if we ever do, we can always pick it up from git history.

Moreover, in this case, the flag is actually useless. Setting it to false would keep on analyzing even if the return value is not discarded (poped from the stack).
