### ISSUE TITLE
synchronize releases of spotbugs, spotbugs-maven-plugin

### ISSUE THREAD

**Issue by Bananeweizen** [spotbugs/spotbugs#861]
Would it be possible to synchronize the releases of the different artifacts? I'm always confused if I see my Eclipse plugin being updated and cannot use the same version in my Jenkins builds, because spotbugs-maven is not released at the same time. E.g. at the time of writing spotbugs 3.11.0 is released since 2 days, spotbugs-maven-plugin is still 3.10.0.

**Comment by KengoTODA** [comment]
As a workaround, you can specify version of tools explicitly. You can find [example for maven](https://spotbugs.readthedocs.io/en/stable/maven.html) in the official document.

**Comment by KengoTODA** [comment]
I personally don't prefer tight release synchronization, because each product should have own pace.

For instance: Recently Gradle plugin has frequent release because Gradle 5 broken some backward compatibility and plugin needed to follow it. If we tightly sync our release, we also need to push SpotBugs core to release even though they has no motivation to do so.  
Actually this is the reason to [separate their repo from core's one](https://github.com/spotbugs/discuss/issues/12). We also have [an idea to have a separated repo for Eclipse plugin](https://github.com/spotbugs/spotbugs/issues/480).

Instead, we core developer can suggest plugin developers to release latest patch version, when we release the latest core version. How do you think about this idea?

**Comment by Bananeweizen** [comment]
I must admit I missed the point that the maven plugin can use a newer release of the core. That will be sufficient, even though it means maintaining 2 version properties instead of 1 in the pom. :)

Regarding coupled versions: I do know other software with multiple integrations, where this is solved by always releasing a new x.y version together for core changes, but to allow totally independent x.y.z, x.y.(z+1) etc. releases of the different parts. I'm aware that this may falsify the meaning of semantical versioning for the non-core parts, if they add huge unrelated features in z+1. It's somewhat of a compromise between exact versioning and more easy to recognize for end users.
